"""Discrete input (FC 0x02) bit map for EA900 G4 — one binary sensor per used bit.

Reserved manufacturer bits (32–47, 79) are omitted — no entities for them.
"""

from __future__ import annotations

from typing import Final

# (bit_index, translation_key, entity_registry_enabled_default, device_class hint)
# device_class: problem | heat | battery | safety | running | connectivity | None
DiscreteBitSpec = tuple[int, str, bool, str | None]

DISCRETE_BIT_SPECS: Final[tuple[DiscreteBitSpec, ...]] = (
    (0, "bus_high_voltage", False, "problem"),
    (1, "bus_low_voltage", False, "problem"),
    (2, "bus_unbalanced", False, "problem"),
    (3, "bus_soft_start_failure", False, "problem"),
    (4, "inverter_soft_start_failure", False, "problem"),
    (5, "inverter_high_voltage", False, "problem"),
    (6, "inverter_low_voltage", False, "problem"),
    (7, "inverter_prohibited", False, "problem"),
    (8, "overtemperature", True, "heat"),
    (9, "output_short_circuit", True, "problem"),
    (10, "overload_fault", True, "problem"),
    (11, "negative_power_abnormality", False, "problem"),
    (12, "shutdown_fault", False, "problem"),
    (13, "parallel_ups_software_mismatch", False, "problem"),
    (14, "sync_signal_abnormality_unused", False, "problem"),
    (15, "sync_pulse_abnormality", False, "problem"),
    (16, "inverter_relay_adhesion", False, "problem"),
    (17, "bus_short_circuit", False, "problem"),
    (18, "can_communication_abnormality", False, "connectivity"),
    (19, "physical_address_conflict", False, "problem"),
    (20, "parallel_ups_model_incompatible", False, "problem"),
    (21, "wrong_battery_numbers", False, "problem"),
    (22, "input_scr_soft_start_failure", False, "problem"),
    (23, "rectifier_scr_fault_unused", False, "problem"),
    (24, "inverter_abnormality", False, "problem"),
    (25, "incorrect_parallel_bypass_wiring", False, "problem"),
    (26, "inverter_open_circuit", False, "problem"),
    (27, "pfc_abnormality", False, "problem"),
    (28, "inverter_capacitor_abnormality", False, "problem"),
    (29, "fan_failed", True, "problem"),
    (30, "epo", True, "safety"),
    (31, "auxiliary_power_lost", False, "problem"),
    (48, "parallel_cables_abnormal", False, "problem"),
    (49, "parallel_ups_settings_error", False, "problem"),
    (50, "reversed_battery_connection", False, "problem"),
    (51, "overload_alarm", True, "problem"),
    (52, "battery_disconnected", True, "problem"),
    (53, "input_overcurrent", False, "problem"),
    (54, "high_battery_voltage", False, "problem"),
    (55, "startup_abnormality", False, "problem"),
    (56, "charger_failure", True, "problem"),
    (57, "eeprom_abnormality", False, "problem"),
    (58, "input_overcurrent_overtime", False, "problem"),
    (59, "low_battery_voltage_fault", True, "battery"),
    (60, "ad_sampling_abnormality", False, "problem"),
    (61, "sync_pulse_abnormality_2", False, "problem"),
    (62, "sync_signal_abnormality_2", False, "problem"),
    (63, "can_communication_abnormality_2", False, "connectivity"),
    (64, "high_bypass_voltage", False, "problem"),
    (65, "bypass_fault", True, "problem"),
    (66, "mains_high_voltage", False, "problem"),
    (67, "mains_frequency_abnormal", False, "problem"),
    (68, "bypass_frequency_out_of_tracking", False, "problem"),
    (69, "bypass_to_inverter_switching_limited", False, "problem"),
    (70, "battery_end_of_discharge", True, "battery"),
    (71, "battery_test_success", False, None),
    (72, "power_on_prohibited", False, "problem"),
    (73, "battery_test_failed", True, "problem"),
    (74, "parallel_current_sharing_abnormality", False, "problem"),
    (75, "inverter_phase_lock_abnormality", False, "problem"),
    (76, "battery_maintenance_success", False, None),
    (77, "battery_maintenance_abnormality", False, "problem"),
    (78, "input_current_unbalanced", False, "problem"),
    (80, "pfc_abnormality_2", False, "problem"),
    (81, "bus_low_to_battery_switching_limited", False, "problem"),
    (82, "mains_abnormality", True, "problem"),
    (83, "bypass_abnormality", False, "problem"),
    (84, "bypass_frequency_abnormality", False, "problem"),
    (85, "inconsistent_inverter_output_voltage_detection", False, "problem"),
    (86, "battery_voltage_abnormality", False, "problem"),
    (87, "inconsistent_bypass_output_voltage_detection", False, "problem"),
    (88, "instable_load_unused", False, "problem"),
    (89, "maintain_bypass_enabled", False, "running"),
    (90, "frequent_overtemperature", False, "heat"),
    (91, "parallel_battery_count_inconsistent", False, "problem"),
    (92, "battery_temp_compensation_abnormal_unused", False, "problem"),
    (93, "instable_bypass_voltage_unused", False, "problem"),
    (94, "test_mode", True, "running"),
    (95, "overload_frequently", False, "problem"),
)
